/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Mock: typeof import('./src/components/virtualList/mock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/upload/index.vue')['default']
    VirtualList: typeof import('./src/components/virtualList/virtualList.vue')['default']
  }
}
